### ISSUE TITLE
newly generated app should actually work

### ISSUE THREAD

**Issue by rubydesign** [meh/lissio#11]
All i get is a blank page. 
No log or any output and no content.
Not the best of starts to get people interested.

I get the Vai col lissio! in the title (from the static) but get no alert and no content.

And when i change the html block it changes nothing. hmm

**Comment by dancinglightning** [comment]
i'm on ruby 2.1.5

I have cloned the repo, but don't know how i would run the command off that. 
I mean to save pushing fixed gems. Though this is so basic it may be worth it.
