### ISSUE TITLE
new does not generate a Gemfile

### ISSUE THREAD

**Issue by rubydesign** [meh/lissio#9]
Here we go :-) And thanks for pushing the new version.

I was wondering why i didn't see bundler output (as one does from new app commands)

A Gemfile is off course needed for your basic workflow, so it should really be included. Can be small though.

**Comment by dancinglightning** [comment]
So reading the source (imho a user shouldn't have to) i see a gemfile is included.
I still think it should be there, if nothing else, with the used lissio gem in it.
